UI5/linter

- README.md
> docs(README.md): Enable REUSE badge

- release-please-config.json
Remove hard-coded initial release version
> ci(release-please): Remove hard-coded initial release version

- .github/workflows/release-please.yml
Resolves https://github.com/SAP/ui5-linter/issues/24
> ci(release-please): Prune npm-shrinkwrap before publishing

- .github/workflows/test.yml
Add a new workflow for os dependent test execution
> ci(test): Add test execution for macos and windows

- test/fixtures/linter/rules/NoDeprecatedApi/sap.ui.require-nested.js
- test/fixtures/linter/rules/NoDeprecatedApi/sap.ui.require-toplevel.js
Findings are already detected.
> test: Update fixtures

- .github/dependabot.yml
https://github.com/SAP/ui5-linter/pull/65 had to be recreated
> ci(dependabot): Trigger dependabot updates on friday

- .github/dependabot.yml
> ci(dependabot): Run npm update checks daily

- src/linter/ui5Types/TypeLinter.ts
- src/linter/ui5Types/amdTranspiler/transpiler.ts
- src/linter/ui5Types/host.ts
- test/lib/linter/js/_helper.ts
This functionality was accidentially removed in 5abbfc1
> refactor: Re-add (debug) output of transformed resources

- docs/PERFORMANCE.md
Updated with current results and added additional libraries to the measurement
Rendered version: https://github.com/SAP/ui5-linter/blob/update-performance-april/docs/PERFORMANCE.md
> docs(PERFORMANCE): Update benchmark results

- README.md
**Thank you for your contribution!** 🙌
To get it merged faster, kindly review the checklist below:
+ Especially the [How to Contribute](https://github.com/SAP/ui5-linter/blob/main/CONTRIBUTING.md#how-to-contribute) section
> docs(README): Add npm badge

- src/formatter/text.ts
Printing message details in a separate line causes the VS Code "Problems" integration to only display one of the lines, as both point to the same line/column in the code.
In addition, replacing multiple spaces solves incorrect message parsing with the $eslint-stylish matcher which expects a "code" after two spaces. Currently no code is printed at all.
> fix: Improve parsing of message details in VS Code problems matcher

- npm-shrinkwrap.json
- package.json
- src/linter/html/parser.ts
- src/linter/ui5Types/SourceFileLinter.ts
- src/linter/ui5Types/amdTranspiler/moduleDeclarationToDefinition.ts
- src/linter/ui5Types/amdTranspiler/rewriteExtendCall.ts
- src/linter/ui5Types/asyncComponentFlags.ts
- src/linter/xmlTemplate/Parser.ts
Bumps @stylistic/eslint-plugin and fixes newly reported stylistic eslint findings.
> build(deps-dev): Bump @stylistic/eslint-plugin from 2.2.1 to 2.2.2

- .github/workflows/ci.yml
- npm-shrinkwrap.json
- package.json
See: https://github.com/SAP/ui5-cli/pull/731
> deps: Pin update-notifier to v7.1.0

- README.md
> docs(README): Add TypeScript

- docs/PERFORMANCE.md
Looks like a slight improvement in the latest release
> docs(PERFORMANCE): Update benchmarks for v0.3.2 and v0.3.3

- src/linter/ui5Types/asyncComponentFlags.ts
- test/fixtures/linter/rules/AsyncComponentFlags/Negative_10/Component.ts
Resolves https://github.com/SAP/ui5-linter/issues/306
> fix(asyncComponentFlags): Fix detection of manifest: 'json' (single quotes)

- .editorconfig
- ava.config.js
- eslint.config.js
- npm-shrinkwrap.json
- package.json
- test/lib/linter/amdTranspiler/parseModuleDeclaration.ts
- test/lib/utils/configManager.ts
Noticed some things while working on the UI5 Tooling TypeScript
enablement
> refactor(config): Minor cleanups in config files

- README.md
- Add latest features
- Update note regarding current and target scope
JIRA: CPOUI5FOUNDATION-909
> docs(README.md): Update documentation with latest scope

- docs/PERFORMANCE.md
No big changes compared to v0.3.5
> docs(PERFORMANCE): Update benchmark measures for v1.0

- README.md
> docs: Add --ui5-config option to README

- src/linter/ui5Types/SourceFileLinter.ts
Custom visitor for ManagedObject metadata.
It's just another variant for achieving this functionality
> feat: Analyze ManagedObject's metadata with own node visitor

- test/fixtures/linter/projects/sap.ui.core/src/sap/ui/base/ManagedObject.js
- test/fixtures/linter/projects/sap.ui.core/src/sap/ui/core/Control.js
- test/fixtures/linter/projects/sap.ui.core/src/sap/ui/core/Element.js
This ensures that the check introduced with
https://github.com/SAP/ui5-linter/pull/371 is actually covered via the
tests.
> test: Add metadata to sap.ui.core base classes

- README.md
**Improve the explanation of how multiple patterns can be used in the --ignore-pattern option, as it is not obvious**
**Thank you for your contribution!** 🙌
To get it merged faster, kindly review the checklist below:
+ Especially the [How to Contribute](https://github.com/SAP/ui5-linter/blob/main/CONTRIBUTING.md#how-to-contribute) section
> Add sample for `--ignore-pattern` to use with mutliple pattern

- resources/api-extract.json
- scripts/metadataProvider/MetadataProvider.ts
- src/utils/ApiExtract.ts
- test/lib/utils/ApiExtract.ts
* refactor(metadata gen): Improve metadata identifier names
* refactor(metadata read): Improve provided methods
* test(ApiExtract): Replace mock data with real api-extract.json
* refactor(metadata gen): Detect exception for UI5 aggregations
> refactor(metadata): Improve generating and reading

- .github/dependabot.yml
- npm-shrinkwrap.json
- package.json
> build(deps-dev): Revert "Bump @types/node from 20.11.0 to 20.14.14"

- docs/Rules.md
- src/linter/messages.ts
- test/lib/linter/messages.ts
Also adds a unit test to ensure all rules are documented.
> docs: Add documentation for new rules

- src/linter/binding/BindingLinter.ts
- test/fixtures/linter/rules/NoGlobals/XMLTemplatingV4.view.xml
Follow-up of https://github.com/SAP/ui5-linter/pull/481
> fix: False-positives for requestCurrencyCodes/requestUnitsOfMeasure

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/issues.yml
- .github/workflows/release-please.yml
- .github/workflows/reuse-compliance.yml
- .github/workflows/test.yml
Runner for ubuntu 24.04 is released. Therefore migrating from `ubuntu-22.04` to `ubuntu-24.04`.
> ci: Use ubuntu 24.04

- .github/workflows/test.yml
Add node v23 to the test matrix
> ci(test.yml): Execute tests with node v23

- README.md
- REUSE.toml
> docs: Update copyright year to 2025

- .github/workflows/ci.yml
- .github/workflows/commitlint.yml
- .github/workflows/e2e.yml
- .github/workflows/issues.yml
- .github/workflows/reuse-compliance.yml
- .github/workflows/test.yml
Declares only the required permissions per workflow.
> ci: Use least privilege principle for permissions

- .licensee.json
- ava-e2e.config.js
- npm-shrinkwrap.json
- package.json
- test/e2e/runtime.ts
- test/fixtures/e2e/runtime/package.json
- test/fixtures/e2e/runtime/src/.library
- test/fixtures/e2e/runtime/src/library.js
- test/fixtures/e2e/runtime/test/qunit/Globals.qunit.js
- test/fixtures/e2e/runtime/test/qunit/testsuite.qunit.html
- test/fixtures/e2e/runtime/test/qunit/testsuite.qunit.js
- test/fixtures/e2e/runtime/ui5.yaml
The tests are executed in the browser before and after running autofix
to ensure that the applied changes are compatible and do not introduce
regressions.
> test(e2e): Add runtime tests for autofix

- README.md
- docs/Migration-Limitations.md
- docs/Scope-of-Autofix.md
> docs: Document migration scope

- docs/Scope-of-Autofix.md
> docs: Autofix restriction for code outside of `sap.ui.define/require`
