UI5/linter

src/detectors/transpilers/xml/Parser.ts
Ignoring them seems safe, so no warning should be produced. There's
typically also nothing a developer can do to resolve the warning.
=> fix(xml-transpiler): Log unknown namespaces as verbose instead of warning

.github/workflows/release-please.yml
Follow-up of https://github.com/SAP/ui5-linter/pull/25
Fixes: https://github.com/SAP/ui5-linter/issues/24
=> fix(npm): Install error "Unsupported platform @esbuild/aix-ppc64@0.19.12"

src/detectors/typeChecker/FileLinter.ts
This reverts commit c8de9c40e98b09bf660aa5b80d158a602acb943f.
Not all libraries have been updated yet as new SAPUI5 patch releases
do not include new versions of every library.
See #29
=> revert: Remove workaround for deprecation text

src/cli/base.ts, test/lib/cli/base.integration.ts, test/lib/cli/base.ts
This change alignes UI5 linter with ESLint (see [1]):
* No errors, maybe warnings: **Use exit code 0**
* At least one error: **Use exit code 1**
* Unexpected error (typically caused by an exception): **Use exit code 2**
**BREAKING CHANGE:** Depending on how UI5 linter is being used, this change
might change the behavior of that particular scenario. For example a
build script might abort further processing, if any linting errors
are detected.
To ignore exit code 1, for example in a bash script, you may use a
construct like this:
```sh
ui5lint && RC=$? || RC=$?
if [[ "$RC" = 2 ]]; then
exit 1
fi
```
JIRA: CPOUI5FOUNDATION-823
[1]: https://eslint.org/docs/latest/use/command-line-interface#exit-codes
=> feat(cli)!: In case of errors, exit with code 1

package.json, tsconfig.json
Only use "tsconfig.build.json" for building and emitting. Use
"tsconfig.json" for checking for compiler errors and for integrating
with typescript-eslint.
The directory structure emitted when using "tsconfig.json" is different
from the regular build in the sense that it contains an additional "src"
directory level.
Configuring "noEmit: true" in the tsconfig file causes issues for the
typescript-eslint integration. Therefore the flag is only set in the npm
script.
=> build: Do not use the linting-tsconfig for emitting files

.github/workflows/test.yml
The "test-build" script compiles the code to check for TypeScript
compilation errors. This is not specific to Node.js / OS and can
therefore be skipped in the matrix. It is also no prerequisite for
running the unit tests, as ava compiles them on-the-fly.
The "test-build" script is still part of the ci.yml workflow.
=> ci: Skip test-build in test matrix

package-lock.json, package.json, src/formatter/coverage.ts, src/formatter/text.ts, src/linter/LinterContext.ts
We can't upgrade eslint itself to v9 until typescript-eslint releases a
compatible version.
=> deps(eslint): Upgrade @eslint/js and @stylistic/eslint-plugin

src/cli/base.ts, test/lib/cli/base.integration.ts
See https://nodejs.org/api/process.html#processexitcode for an explanation of process.exit and process.exitCode and https://nodejs.org/api/process.html#a-note-on-process-io for an explanation when I/O might be sync or async.
Additionally writes a newline after format "json" has been written. This prevents strange behavior in at least zsh when output is not terminated by a newline.
=> fix: Don't exit synchronously when there still might be async I/O

npm-shrinkwrap.json, package.json
This change updates `@sapui5/types` to 1.120.13 which is vital for https://github.com/SAP/ui5-linter/pull/73
=> deps: Bump @sapui5/types to 1.120.13

src/linter/ui5Types/TypeLinter.ts, src/linter/ui5Types/amdTranspiler/transpiler.ts
Disable error reporting for JavaScript resources. We don't retrieve the reported errors anyways. This change significantly improves the speed of the AMD to ESM transpiler as well as the type checker.
For the transpiler, setting this flag only takes effect since TypeScript v5.5.2 (which we are using now).
*Based on https://github.com/SAP/ui5-linter/blob/main/docs/PERFORMANCE.md#large-library-openui5-sapm*
ui5-linter Ref | Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|:---|---:|---:|---:|---:|
| b81d416 (main) | `ui5lint` | 37.806 ± 0.828 | 37.120 | 39.611 | Baseline |
| 3fba8f6 (this PR) | `ui5lint` | 32.798 ± 0.957 | 31.587 | 34.433 | **-13%** |
=> fix: Disable TS-compiler checks for JavaScript resources

.github/workflows/ci.yml, .github/workflows/release-please.yml, .github/workflows/test.yml, package.json
BREAKING CHANGE: Support for older Node.js has been dropped.
Only Node.js 20.11.x and >=22.0.0 as well as npm v8 or higher are supported.
JIRA: CPOUI5FOUNDATION-833
=> feat!: Drop support for node v18, v21

eslint.config.js, npm-shrinkwrap.json, package.json, src/cli/base.ts, src/linter/xmlTemplate/Parser.ts
JIRA: CPOUI5FOUNDATION-827
In order to support TS eslint checks, this repo depends not only on EsLint, but also on complementary dependencies: `typescript-eslint` & `@stylistic/eslint-plugin`. In order to meet their peerDependency requirements for ESLint 9, those modules need to get `alpha` & `beta` releases:
- `"typescript-eslint": "8.0.0-alpha.60"`
- `"@stylistic/eslint-plugin": "2.6.0-beta.1"`
More details: https://github.com/typescript-eslint/typescript-eslint/issues/8211
Edit: `typescript-eslint` & `@stylistic/eslint-plugin` have been released and the automatic bumps would be suppressed and integrated within this change: https://github.com/SAP/ui5-linter/pull/231 https://github.com/SAP/ui5-linter/pull/234
=> deps: Bump eslint from 8.57.0 to 9.8.0

.licensee.json, npm-shrinkwrap.json, package.json
Follow-up of https://github.com/SAP/ui5-linter/pull/242
The problematic dependency is not used anymore by the "boxen" package.
=> deps: Switch back to latest version of update-notifier

eslint.config.js, npm-shrinkwrap.json, src/formatter/lib/resolveLinks.ts, src/linter/xmlTemplate/Parser.ts, src/linter/xmlTemplate/generator/Writer.ts
With the introduction of ESLint 9 and the update of `typescript-eslint`, there are new rules that will be applied to the code. Those rules are mainly focused on Regex patterns.
With https://github.com/SAP/ui5-linter/pull/230 those rules have been turned off to keep it consistent with the old behavior.
This change aims to enable those rules.
**Note:** The base for this change is https://github.com/SAP/ui5-linter/pull/230 and not the **main** branch. This way it's clearer what the real changes are.
=> refactor: Enable eslint RegEx rules

release-please-config.json
- remove boolean flag "prerelease" to no longer produce v0 releases
- remove no longer needed flags "bump-minor-pre-major" and "bump-patch-for-minor-pre-major"
JIRA: CPOUI5FOUNDATION-909
=> ci(release-please): Remove prerelease configuration

README.md
=> docs: Provide documentation for configuration "files"

src/linter/linter.ts
The matchedPatterns are only relevant for the current lint run and
should not be stored in a static set that won't be cleared between
multiple lint runs in the same process. There doesn't seem to be a need
to have the set statically available.
=> refactor: Don't use static set for matchedPatterns

src/linter/linter.ts, test/lib/linter/linter.ts
Providing an ignore pattern e.g. via CLI `--ignore-pattern` did not work
when the path started with "./".
Fixes: https://github.com/SAP/ui5-linter/issues/407
=> fix: Match ignore-pattern starting with "./"

.licensee.json, npm-shrinkwrap.json, package.json
Downgrading the package and making sure that "npm test" runs the check.
Also removes exceptions of packages that now declare a valid license.
=> ci: Fix licensee error of @typescript-eslint/parser@8.18.0

src/linter/linter.ts, test/fixtures/linter/projects/legacy-dirs/legacy.app.a/WebContent/manifest.json, test/fixtures/linter/projects/legacy-dirs/legacy.app.b/src/main/webapp/manifest.json, test/fixtures/linter/projects/legacy-dirs/legacy.lib.a/src/main/jslib/.library, test/fixtures/linter/projects/legacy-dirs/legacy.lib.b/src/main/uilib/.library, test/fixtures/linter/projects/legacy-dirs/legacy.lib.c/src/main/js/.library, test/lib/linter/linter.ts
Enhance compatibility for legacy UI5 projects that do not include a
ui5.yaml and do not use current best practice directory structures like
'webapp' for apps and 'src'/'test' for libraries.
In addition to those directories we now also check and eventually use
the following directories:
Applications:
* src/main/webapp
* WebContent
Libraries:
* src/main/jslib (+ src/test/jslib)
* src/main/uilib (+ src/test/uilib)
* src/main/js (+ src/test/js)
=> feat(linter): Extend project initialization fallbacks

npm-shrinkwrap.json, package.json
Tests are failing with v2.3.2. It seems like events are emitted in a
different order now. Pinning to last working version for now to get
automatic updates working again for the repository.
=> deps(sax-wasm): Pin dependency to v2.2.4

src/linter/linter.ts, src/utils/ConfigManager.ts, test/lib/linter/linter.ts, test/lib/utils/ConfigManager.ts
`import(path)` does not accept absolute Windows-paths since those seem to get confused with URLs.
Before, this was mitigated by always calculating a relative path (relative to the UI5 linter install directory). This however breaks on Windows if the target project is located on another drive as reported in https://github.com/SAP/ui5-linter/issues/458
Instead convert all paths to `file://`-URLs before passing them to `import()`.
Also, in linter.ts, enforce the project root path to always be absolute to simplify handling the path later on.
Resolves https://github.com/SAP/ui5-linter/issues/458
=> fix(ConfigManager): Resolve ESM import exception on Windows

src/cli/base.ts, src/index.ts
Behavior should be identical to the linter CLI, where a fallback is done if no ui5.yaml can be found. This is only possible if no path is specified for the parameter, hence removing the defaulting in the API.
=> fix(API): Remove ui5Config parameter defaulting

npm-shrinkwrap.json, package.json
This ensures that no new features are used that are not available in the minimum supported Node.js version.
=> ci: Use @types/node based on minimum Node.js version

npm-shrinkwrap.json, package.json, src/linter/dotLibrary/DotLibraryLinter.ts, src/linter/html/HtmlReporter.ts, src/linter/html/parser.ts, src/linter/html/transpiler.ts, src/linter/xmlTemplate/Parser.ts, src/linter/xmlTemplate/transpiler.ts, src/utils/xmlParser.ts, test/lib/utils/xmlParser.ts
Upgrades package "sax-wasm" to latest major version.
=> deps: Bump sax-wasm from 2.2.4 to 3.0.3

src/linter/ui5Types/SourceFileLinter.ts
Resolves: https://github.com/SAP/ui5-linter/pull/499#discussion_r1930628950
=> fix: Provide check for alternative names of the properties

test/fixtures/linter/projects/com.ui5.troublesome.app/ui5lint-custom-broken.config.cjs
CodeQL code scan complains about this file being broken. This is a case we test for the config manager. So, wrapping it in a JSON.parse to avoid the error there, but keep the test case valid.
=> fix: CodeQL scan

.nycrc, src/cli/base.ts, src/index.ts, src/linter/lintWorkspace.ts, src/linter/linter.ts, src/linter/ui5Types/LanguageServiceHostProxy.ts, src/linter/ui5Types/SharedLanguageService.ts, src/linter/ui5Types/TypeLinter.ts, src/linter/ui5Types/host.ts, test/lib/cli/base.ts, test/lib/linter/_linterHelper.ts, test/lib/linter/linter.ts, test/lib/linter/ui5Types/LanguageServiceHostProxy.ts, test/lib/linter/ui5Types/SharedLanguageService.ts
Switching from just a `Program` to the `LanguageService` has several benefits:
- Adding/changing source files is possible without having to create a new program manually while keeping all unchanged files cached
- Host implementation is more lightweight
- A shared `LanguageService` can be used to improve performance when linting multiple independent files/projects within the same process/thread. This is currently only used internally by the tests, but a new public API can be easily provided.
=> refactor: Use TypeScript LanguageService

src/linter/ui5Types/LanguageServiceHostProxy.ts, src/linter/ui5Types/host.ts
Caching the script snapshot instances further improves the performance
when re-using a shared service instance.
=> refactor: Improve caching of shared type files

src/linter/ui5Types/SourceFileLinter.ts
fixes: https://github.com/SAP/ui5-linter/pull/480#discussion_r1938892332
=> refactor: Consider ManagedObject as base class for bind* & applySettings

.github/workflows/test.yml
Runner for windows 2025 is released. Therefore migrating from `windows-2022` to `windows-2025`.
=> ci(test.yml): Use windows 2025

.github/workflows/test.yml
Runner for macos 15 is released. Therefore migrating from `macos-14` to `macos-15`.
=> ci(test.yml): Use macos 15

src/linter/ui5Types/TypeLinter.ts
The "libReplacement" flag has been added with TypeScript 5.8.
As we don't use the alternative lookup, we can disable it to prevent
checking for the replacement packages.
=> perf: Prevent unnecessary TypeScript libReplacement lookup

src/linter/ui5Types/SourceFileLinter.ts, src/linter/ui5Types/SourceFileReporter.ts, src/linter/ui5Types/TypeLinter.ts, src/linter/ui5Types/asyncComponentFlags.ts, test/lib/linter/_linterHelper.ts, test/lib/linter/linter.ts
Create SourceFileReporter at a central place to ease adding message for
different files.
Reduced the number of arguments of the SourceFileLinter constructor
by passing the TypeLinter instance.
Adjusted the mocking of getDeprecationText in the tests to prevent
having to always align the SourceFileLinter constructor args in the tests.
=> refactor: TypeLinter / SourceFileLinter

.github/workflows/test.yml, ava.config.js
Sometimes the default timeout of 10s per test is not enough within
the GitHub Actions CI.
=> ci: Increase test timeout / Don't fail fast on CI

.github/dependabot.yml, .github/workflows/dependabot-auto-merge.yml
Depedabot will create PRs for new minor versions of @sapui5/types again,
however they will not be auto-merged. Instead, a notice is added to the
PR body, requesting a developer to execute the update script and amend
the commit before manually merging the update.
=> ci(dependabot): Enable @sapui5/types updates again

README.md
Just a suggestion to add to this to the README to save the output of the `format` option
=> docs: Add usage example for format option and saving output to file

.github/CODEOWNERS, .github/dependabot.yml
With https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/ GitHub announced the removal of the `reviewers` property end of May 2025. Therefore switching to the recommended `CODEOWNERS` file based setup.
=> ci: Replace reviewers config of dependabot by CODEOWNERS file

.github/workflows/test.yml, src/untyped.d.ts, test/e2e/compare-ui5lint-fix-snapshots.ts, test/lib/linter/_linterHelper.ts
node:fs#Dirent.path has been deprecated in Node v20.12.0 and replaced by .parentPath which was added in the same v20.12.0 release: https://nodejs.org/docs/latest-v20.x/api/fs.html#direntparentpath
Node v24 has removed the deprecated dirent.path.
Since we still support Node v20.11.0, we need to check for one and fallback to the other depending on availability.
=> test: Fix tests on Node v24, extend CI matrix

src/linter/ui5Types/SourceFileLinter.ts, src/linter/ui5Types/SourceFileReporter.ts, src/linter/ui5Types/asyncComponentFlags.ts
Introducing an options object instead of individual arguments allows
for easier extensibility when new information needs to be passed to
messages.
The optional args handling has been removed to also simplify the code.
The changes revealed a problem with the return type of
"isUi5ClassDeclaration", which has been fixed.
=> refactor(SourceFileReporter): Convert addMessage args to options

src/linter/ui5Types/TypeLinter.ts, src/linter/ui5Types/host.ts, test/lib/linter/ui5Types/host.ts
This allows to create a host with the right compiler options which is
helpful to write unit tests for TypeScript AST functionality without
having to run the full linter.
=> refactor(ui5Types/host): Improve isolated usage of host and add tests

src/linter/ui5Types/fix/AccessExpressionBaseFix.ts, src/linter/ui5Types/fix/AccessExpressionFix.ts, src/linter/ui5Types/fix/BaseFix.ts, src/linter/ui5Types/fix/CallExpressionFix.ts
Some parameters where available to generator-fixes even though those
don't use them.
=> refactor(autofix): Straighten out fix parameters

.github/workflows/test.yml
Node v23 has reached end of life.
https://nodejs.org/en/about/previous-releases
=> ci(test.yml): Remove Node v23 from test matrix

src/autofix/autofix.ts, src/linter/LinterContext.ts, src/linter/binding/BindingLinter.ts, src/linter/dotLibrary/DotLibraryLinter.ts, src/linter/fileTypes/linter.ts, src/linter/html/HtmlReporter.ts, src/linter/html/transpiler.ts, src/linter/lintWorkspace.ts, src/linter/manifestJson/ManifestLinter.ts, src/linter/manifestJson/ManifestReporter.ts, src/linter/ui5Types/SourceFileLinter.ts, src/linter/ui5Types/asyncComponentFlags.ts, src/linter/xmlTemplate/Parser.ts, src/linter/xmlTemplate/transpiler.ts, src/linter/yaml/YamlLinter.ts, test/lib/linter/LinterContext.ts
This change aims to align the signature of `addLintingMessage` and `addLintingMessages`. The core change is that now `addLintingMessage` supports `fix` and `ui5Types` arguments
=> refactor: Align arguments between addLintingMessage & addLintingMessages

.github/workflows/release-please.yml
Using trusted publishing via OIDC for npm publishing. This makes the use of npm tokens obsolete and improves security.
See: https://docs.npmjs.com/trusted-publishers
=> ci(release-please): Enable trusted publishing

.github/workflows/ci.yml
This will add `continue-on-error` to the Coveralls report upload step in the job "CI / General checks...".
In case of an error with this step (e.g. the Coveralls service is temporarily down) the job continues as normal and does NOT fail.
=> ci(github-actions): Ignore Coveralls errors
